import type { Metadata } from "next";
import '@fontsource/roboto'
import '@fontsource/rubik'
import { CssBaseline } from "@mui/material";
import './globalicon.css';

export const metadata: Metadata = {
  title: "Bushido Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <CssBaseline />
      <body>{children}</body>
    </html>
  );
}
